### ISSUE TITLE
公式解析有问题

### ISSUE THREAD

**Issue by qigangliu** [keithyin/mynotes#1]
看了你在CSDN上关于这篇文章的前半部分，感觉写的很好，想看一下后半部分，但这里文章中的公式不能解析，是否能调整一下，拜读一下你的文章。

**Comment by keithyin** [comment]
我是用 typora 写的然后上传的，您可以 把文件保存下来 用 typora （或其它 markdown 编辑器）查看，关于网页上的解析问题，我也没啥解决办法。。。
